site_name: Praktikum zur LVA "Nutzerzentrierte Softwareentwicklung"

nav:
  - 'Startseite': 'index.md'
  - 'Vorbemerkung': 'vorbemerkung.md'
  - 'Projektmappe': 'projektmappe.md'
  - 'Termin 0: Android Studio': 'termin1.md'
  - 'Termin 1: User Research': 'termin2.md'
  - 'Termin 2: UI Entwurf': 'termin3.md'
  - 'Termin 3: Layout': 'termin4.md'
  - 'Termin 4: Logik': 'termin5.md'
  - 'Termin 5: Usability': 'termin6.md'

theme:
  name: 'material'
  language: 'de'

  palette:
    primary: 'blue'
    accent: 'red'
  
  feature:
    tabs: false

  font:
    text: 'Barlow Semi Condensed'
    code: 'Roboto mono'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascript/extra.js'
    
markdown_extensions:
  - admonition
  - smarty:
      smart_angled_quotes: true
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: false
  - meta
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      linenums: true
      guess_lang: false

  
