site_name: "Einführung in Flutter und Dart"

nav:
  - 'Main Page': 'index.md'
  - 'Dart': './themen/dart.md'


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        primary: deep purple
        accent: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto Condensed
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  
  language: de
  
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit

extra_css:
  - 'stylesheets/extra_new.css'

extra:
  social:
    - icon: fontawesome/solid/person-biking 
      link: https://fbi.h-da.de/~s.zander
      name: personal page of Prof. Dr. Stefan Zander at h_da

copyright: Copyright &copy; 2017 - 2024 – Prof. Dr. Stefan Zander

repo_url: https://github.com/StefanZander/lecture_notes/tree/master/hci/flutter/skript/html
repo_name: flutter docu

edit_uri: docs/


plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: false
      type: custom


markdown_extensions:
  - abbr
  - admonition
  - smarty:
      smart_angled_quotes: true  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic