site_name: "Introduction to Flutter and Dart"

nav:
  - 'Main Page': 'index.md'
  - 'Introduction': './themen/flutter_introduction.md'
  - 'Dart': './themen/dart.md'
  - 'Building an App': './themen/designing_an_app.md'
  - 'Widgets': './themen/widgets.md'
  - 'Interactivity': './themen/behaviour.md'
  - 'Layout': './themen/layout.md'  
  - 'Navigational Elements': './themen/navigation.md'
  - 'Screen Navigation': './themen/screen_navigation.md'
  - 'Data Exchange': './themen/data_exchange.md'  
  - 'State Management': './themen/state_management.md' 
  - 'Collections': './themen/collections.md' 
  - 'Persistence': './themen/persistence.md'  
  - 'Fetching': './themen/fetching.md'  
  - 'JSON': './themen/json.md'
  - 'Asychronity': './themen/asynchronity.md'
  - '.gitignore': './themen/gitignore.md'
  - 'SnackBar': './themen/snackbar.md'

extra_css:
  - stylesheets/extra.css


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        primary: deep purple
        accent: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto Condensed
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  
  language: de
  
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate

extra:
  social:
    - icon: fontawesome/solid/person-biking 
      link: https://fbi.h-da.de/~s.zander
      name: h_da profile page of Prof. Dr. Stefan Zander

copyright: Copyright &copy; 2017 - 2024 – Prof. Dr. Stefan Zander

repo_url: https://github.com/StefanZander/lecture_notes/tree/master/hci/flutter/skript/html
repo_name: flutter docu

edit_uri: docs/


plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: false
      type: custom


markdown_extensions:
  - abbr
  - admonition
  - smarty:
      smart_angled_quotes: true  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
