site_name: Praxisphase und Abschlussarbeit

nav:
  - 'Startseite': 'index.md'
  - 'Praxisphase': 'praxisphase.md'
  - 'Exposé': 'expose.md'
  - 'Bachelorarbeit': './bachelorarbeit/q_and_a.md'
  - 'Tipps': 'lernen_lernen.md'


theme:
  name: 'material'
  language: 'de'

  palette:
    primary: 'blue'
    accent: 'red'

  feature:
    tabs: false

  font:
    text: 'Barlow Semi Condensed'
    code: 'Fira mono'

extra_css:
  - 'css/extra.css'

extra_javascript:
  - 'javascript/extra.js'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: false
  - meta
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde