site_name: "Scientific Writing for Computer Science"

nav:
  - 'Main Page': 'index.md'
  - 'Objectives': 'objectives.md'
  - 'Organisation': 'organisation.md'
  - 'Schedule': 'schedule.md'
  - 'Scientific Writing': 'scientific_writing.md'  
  - 'Structure': 'structure.md' 
  - 'MS0: Introductory Material': 'milestone0.md'
  - 'MS1: Group and Topic': 'milestone1.md'
  - 'MS2: Factsheet & Abstract': 'milestone2.md'
  - 'MS3: Paper Draft': 'milestone3.md'
  - 'MS4: Review': 'milestone4.md'
  - 'MS5: Final Presentation': 'milestone5.md'
  - 'MS6: Final Paper': 'milestone6.md'
  - 'Common Mistakes': 'common_mistakes.md' 
  - 'Tipps': 'good_paper.md'

theme:
  name: material
  color_mode: dark
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        primary: deep purple
        accent: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto Condensed
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  
  language: de
  
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit

extra_css:
  - 'stylesheets/extra_new.css'

extra:
  social:
    - icon: fontawesome/solid/person-biking 
      link: https://fbi.h-da.de/~s.zander
      name: personal page of Prof. Dr. Stefan Zander at h_da

copyright: Copyright &copy; 2017 - 2025 – Prof. Dr. Stefan Zander

repo_url: https://github.com/StefanZander/lecture_notes/tree/master/swcs/html
repo_name: swcs

edit_uri: docs/


plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: false
      type: custom


markdown_extensions:
  - abbr
  - admonition
  - smarty:
      smart_angled_quotes: true  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic