site_name: "Scientific Writing for Computer Science"

nav:
  - 'Main Page': 'index.md'
  - 'Objectives': 'objectives.md'
  - 'Organisation': 'organisation.md'
  - 'Exposé': 'expose.md'

theme:
  name: 'material'
  language: 'de'

  palette:
    primary: 'blue'
    accent: 'red'

  feature:
    tabs: false

  font:
    text: 'Zilla Slab'
    code: 'Fira mono'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascript/extra.js'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: false
  - meta
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde