site_name: Praktikum zu "Entwicklung webbasierter Anwendungen" im Sommersemester 2019

nav:
  - 'Startseite': 'index.md'
  - 'Vorbemerkungen': 'vorbemerkung.md'
  - 'Anforderungen': 'anforderungen.md'
  - 'Selbststudium I: Anforderungen und HTML': 'termin0.md'
  - 'Termin 1: PHP – Erzeugung von Webseiten': 'termin1.md'
  - 'Termin 2: PHP – Objektorientierung und Datenbanken': 'termin2.md'
  - 'Termin 3: PHP - Sessions, Sicherheit und AJAX-Vorbereitung': 'termin3.md'
  - 'Termin 4: Client-seitige Interaktion mit JavaScript, AJAX und DOM': 'termin4.md'
  - 'Selbststudium II: Responsives Design': 'termin4_5.md'
  - 'Termin 5: Abnahme': 'termin5.md'

theme:
  name: 'material'
  language: 'de'

  palette:
    primary: 'blue'
    accent: 'red'

  feature:
    tabs: false

  font:
    text: 'Zilla Slab'
    code: 'Fira mono'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascript/extra.js'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: false
  - meta
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde