site_name: HCI-Praktikumsaufgaben

nav:
  - 'Startseite': 'index.md'
#  - 'NZSE-Tagebuch': 'tagebuch.md'
#  - 'Corona-Modus': 'corona.md'
#  - 'Arbeiten mit BBB': 'bbb.md'
  - 'Vorbemerkung': 'vorbemerkung.md'
  - 'Themen': 'angebotene_themen.md'
  - 'Projektmappe': 'projektmappe.md'
  - 'Vorbereitung: Flutter Tutorial': 'termin0.md'
  - 'Termin 1: User Research': 'termin1.md'
  - 'Termin 2: UI Entwurf': 'termin2.md'
  - 'Termin 3: Layout': 'termin3.md'
  - 'Termin 4: Logik': 'termin4.md'
  - 'Termin 5: App-Präsentation': 'termin5.md'
  - 'Abschluss: Usability': 'termin6.md'



theme:
  name: material
  palette:
    primary: blue
    accent: deep orange
  font:
    text: Roboto Condensed
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  language: de
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fbi.h-da.de/~s.zander
      name: hda profile page of Prof. Dr. Stefan Zander

copyright: Copyright &copy; 2017 - 2023 – Prof. Dr. Stefan Zander

repo_url: https://github.com/StefanZander/lecture_notes/tree/master/hci/praktikum/html
repo_name: /hci/praktikum

edit_uri: docs/

plugins:
  - search:
      lang: de
  - git-revision-date-localized:
      enable_creation_date: false
      type: custom

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  
